version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: ng02
        ports:
            - "8000:8000"
        volumes:
            - ./deploy/nginx:/etc/nginx/conf.d
            - ./static:/static
            - ./src/media:/media
        depends_on:
            - web
    web:
        build: .
        container_name: dg02
        command: bash -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && uwsgi --ini /usr/local/etc/undercloud.ini"
        depends_on:
            - db
        volumes:
            - ./src:/src
            - ./deploy/uwsgi:/usr/local/etc/
            - ./static:/static
            - ./src/media:/media
        expose:
            - "8000"
    db:
        image: postgres:latest
        container_name: ps02
